import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const API_KEY = process.env.LLM_API_KEY;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BLOG_DIR = path.join(__dirname, '../src/components/blog');

async function generateBlog() {
  if (!API_KEY) {
    console.error("Fout: Geen LLM_API_KEY geconfigureerd in GitHub Secrets.");
    process.exit(1);
  }

  const prompt = `
Je werkt in de repository enercalculatie-website.
Taak: schrijf EEN nieuw, origineel Nederlands blogartikel voor de kennisbank, gericht op installateurs in de verduurzamingsbranche.

Instructies:
- Gebruik actuele thema's: RVO (ISDE), ACM, Netbeheer Nederland.
- Schrijf in professioneel Nederlands, u-vorm, gericht op de installateur.

Lever de output exact aan in dit blok:

---START_CODE---
import { SEO } from '../SEO';
import { BlogPostLayout } from './BlogPostLayout';

export const meta = {
  slug: 'verzin-een-logische-slug',
  title: 'Titel van de blog',
  description: 'SEO beschrijving van ca. 150 tekens.',
  date: '${new Date().toISOString().split('T')[0]}',
  excerpt: 'Korte inleiding.',
  tags: ['Tag1', 'Tag2'],
  keyPoints: ['Punt 1', 'Punt 2', 'Punt 3', 'Punt 4']
};

export default function AutoGeneratedBlogArticle() {
  return (
    <>
      <SEO
        title={\`\${meta.title} | EnerCalculatie\`}
        description={meta.description}
        canonical={\`https://www.enercalculatie.nl/blog/\${meta.slug}\`}
      />
      <BlogPostLayout post={meta}>
        <p className="text-slate-700 leading-relaxed mb-4">
          Inhoud...
        </p>
      </BlogPostLayout>
    </>
  );
}
---END_CODE---
`;

  console.log("Verbinding maken met OpenRouter API...");
  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`
      },
      body: JSON.stringify({
        model: 'deepseek/deepseek-chat', 
        messages: [{ role: 'user', content: prompt }]
      })
    });

    const data = await response.json();
    
    if (!data.choices || !data.choices[0]) {
      console.error("API Foutmelding:", data);
      process.exit(1);
    }

    const responseText = data.choices[0].message.content;
    const codeMatch = responseText.match(/---START_CODE---([\s\S]*?)---END_CODE---/);

    if (!codeMatch) {
      console.error("Fout: Geen codeblok gevonden in de API-respons.");
      process.exit(1);
    }

    const code = codeMatch[1].trim();

    if (!fs.existsSync(BLOG_DIR)){
        fs.mkdirSync(BLOG_DIR, { recursive: true });
    }

    const dateStr = new Date().toISOString().split('T')[0].replace(/-/g, '');
    const fileName = `BlogInstallatie_${dateStr}.tsx`;
    const filePath = path.join(BLOG_DIR, fileName);

    fs.writeFileSync(filePath, code);
    console.log(`✅ Component succesvol weggeschreven naar: ${filePath}`);
    console.log("✅ Metadata is nu onderdeel van het component zelf. Build blijft stabiel.");

  } catch (error) {
    console.error("Netwerk- of verwerkingsfout:", error);
    process.exit(1);
  }
}

generateBlog();
