import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const API_KEY = process.env.LLM_API_KEY;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BLOG_DIR = path.join(__dirname, '../src/components/blog');
const CONTENT_FILE = path.join(__dirname, '../src/content/blogPosts.ts');

async function generateBlog() {
  if (!API_KEY) {
    console.error("Fout: Geen LLM_API_KEY geconfigureerd in GitHub Secrets.");
    process.exit(1);
  }

  let existingContent = "";
  try {
    existingContent = fs.readFileSync(CONTENT_FILE, 'utf-8');
  } catch (e) {
    console.log("blogPosts.ts niet gevonden of leesfout. We gaan door zonder context.");
  }

  const prompt = `
Je werkt in de repository enercalculatie-website.
Taak: schrijf EEN nieuw, origineel Nederlands blogartikel voor de kennisbank, gericht op installateurs in de verduurzamingsbranche.

Instructies:
- Het onderwerp mag NIET al voorkomen in deze lijst: ${existingContent.substring(0, 1000)}...
- Gebruik actuele thema's: RVO (ISDE), ACM, Netbeheer Nederland.
- Schrijf in professioneel Nederlands, u-vorm, gericht op de installateur.
- Genereer UITSLUITEND de rauwe React/TypeScript code. Geen markdown blokken (\`\`\`tsx), geen uitleg, alleen de code.

Gebruik EXACT deze structuur (vervang de dummy-teksten door jouw artikel):

import { SEO } from '../SEO';
import { BlogPostLayout } from './BlogPostLayout';

const post = {
  slug: 'verzin-een-logische-slug-hier',
  title: 'Jouw Gegenereerde Titel Hier',
  description: 'Korte SEO omschrijving van ca. 150 tekens.',
  date: '${new Date().toISOString().split('T')[0]}',
  excerpt: 'Korte inleidende tekst.',
  tags: ['Tag1', 'Tag2', 'Installatiebranche'],
  keyPoints: ['Kernpunt 1', 'Kernpunt 2', 'Kernpunt 3', 'Kernpunt 4']
};

export default function AutoGeneratedBlogArticle() {
  return (
    <>
      <SEO
        title={\`\${post.title} | EnerCalculatie\`}
        description={post.description}
        canonical={\`https://www.enercalculatie.nl/blog/\${post.slug}\`}
      />
      <BlogPostLayout post={post}>
        <p className="text-slate-700 leading-relaxed mb-4">
          Inleiding van het artikel...
        </p>

        <h2 className="text-xl md:text-2xl font-bold text-slate-800 mt-8 mb-4">Kopje 1</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Alinea tekst...
        </p>

        <ul className="list-disc pl-6 mb-6 text-slate-700">
          <li>Lijst item 1</li>
          <li>Lijst item 2</li>
        </ul>
      </BlogPostLayout>
    </>
  );
}
`;

  console.log("Verbinding maken met OpenRouter API...");
  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`
      },
      body: JSON.stringify({
        model: 'deepseek/deepseek-chat', 
        messages: [{ role: 'user', content: prompt }]
      })
    });

    const data = await response.json();
    
    if (!data.choices || !data.choices[0]) {
      console.error("API Foutmelding:", data);
      process.exit(1);
    }

    let code = data.choices[0].message.content;
    code = code.replace(/```tsx?\n/g, '').replace(/```/g, '').trim();

    if (!fs.existsSync(BLOG_DIR)){
        fs.mkdirSync(BLOG_DIR, { recursive: true });
    }

    const dateStr = new Date().toISOString().split('T')[0].replace(/-/g, '');
    const fileName = `BlogInstallatie_${dateStr}.tsx`;
    const filePath = path.join(BLOG_DIR, fileName);

    fs.writeFileSync(filePath, code);
    console.log(`✅ Succesvol weggeschreven naar: ${filePath}`);

  } catch (error) {
    console.error("Netwerk- of verwerkingsfout:", error);
    process.exit(1);
  }
}

generateBlog();
