import { SEO } from '../SEO';
import { BlogPostLayout } from './BlogPostLayout';

export const meta = {
  slug: 'actuele-regels-verduurzaming-2024',
  title: 'Actuele regels voor verduurzaming: wat installateurs moeten weten in 2024',
  description: 'Overzicht van belangrijke regels voor installateurs in de verduurzamingsbranche, inclusief ISDE-subsidies, ACM-voorschriften en netbeheerrichtlijnen.',
  date: '2024-02-15',
  excerpt: 'Als installateur in de verduurzamingsbranche is het essentieel om op de hoogte te blijven van de laatste regels. Dit artikel geeft u een actueel overzicht.',
  tags: ['ISDE', 'ACM', 'Netbeheer', 'Verduurzaming'],
  keyPoints: [
    'Update ISDE-subsidiecriteria voor 2024',
    'Nieuwe ACM-voorschriften voor transparantie',
    'Wijzigingen in netbeheerprocedures',
    'Praktische tips voor compliance'
  ]
};

export default function AutoGeneratedBlogArticle() {
  return (
    <>
      <SEO
        title={`${meta.title} | EnerCalculatie`}
        description={meta.description}
        canonical={`https://www.enercalculatie.nl/blog/${meta.slug}`}
      />
      <BlogPostLayout post={meta}>
        <p className="text-slate-700 leading-relaxed mb-4">
          De verduurzamingsbranche ontwikkelt zich snel, en als installateur is het uw taak om klanten optimaal te adviseren. In dit artikel bespreken we de belangrijkste regelgevende updates voor 2024 waar u rekening mee moet houden.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-3">ISDE-subsidies: nieuwe criteria voor 2024</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          De RVO heeft enkele wijzigingen doorgevoerd in de Investeringssubsidie Duurzame Energie (ISDE). Let vooral op:
        </p>
        <ul className="list-disc pl-5 mb-4">
          <li className="mb-2">Hogere subsidiebedragen voor hybride warmtepompen</li>
          <li className="mb-2">Uitbreiding van de lijst met erkende installateurs</li>
          <li className="mb-2">Striktere documentatie-eisen bij aanvraag</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6 mb-3">ACM: nadruk op transparantie</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          De Autoriteit Consument & Markt (ACM) heeft nieuwe richtlijnen gepubliceerd voor energieadvies. Belangrijkste punten:
        </p>
        <ul className="list-disc pl-5 mb-4">
          <li className="mb-2">Verplichte vermelding van besparingsgaranties</li>
          <li className="mb-2">Duidelijker specificeren van terugverdientijden</li>
          <li className="mb-2">Strengere handhaving op misleidende claims</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6 mb-3">Netbeheer Nederland: vereenvoudigde procedures</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Netbeheer Nederland introduceert dit jaar enkele vereenvoudigingen in de aansluitprocedures voor duurzame installaties:
        </p>
        <ul className="list-disc pl-5 mb-4">
          <li className="mb-2">Kortere doorlooptijden voor kleinere projecten</li>
          <li className="mb-2">Digitale aanmelding via standaardplatforms</li>
          <li className="mb-2">Nieuwe richtlijnen voor teruglevervoorzieningen</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6 mb-3">Praktische tips voor installateurs</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Om optimaal te profiteren van deze ontwikkelingen adviseren wij:
        </p>
        <ul className="list-disc pl-5 mb-4">
          <li className="mb-2">Volg de verplichte bijscholing over ISDE-wijzigingen</li>
          <li className="mb-2">Implementeer standaarddocumentatie voor ACM-compliance</li>
          <li className="mb-2">Maak gebruik van de nieuwe netbeheertools</li>
        </ul>
      </BlogPostLayout>
    </>
  );
}