import { SEO } from '../SEO';
import { BlogPostLayout } from './BlogPostLayout';

const post = {
  slug: 'rvo-isde-2026-wijzigingen',
  title: 'ISDE 2026: belangrijke wijzigingen voor installateurs in de verduurzamingsbranche',
  description: 'Ontdek de belangrijkste wijzigingen in de ISDE-regeling voor 2026 en hoe u uw klanten optimaal kunt adviseren over warmtepompen en isolatie.',
  date: '2026-07-15',
  excerpt: 'De ISDE-regeling ondergaat in 2026 enkele belangrijke wijzigingen waar u als installateur rekening mee moet houden.',
  tags: ["ISDE", "RVO", "Warmtepompen", "Verduurzaming"],
  keyPoints: [
    "Verhoogde subsidiebedragen voor hybride warmtepompen",
    "Nieuwe eisen voor isolatie bij warmtepompinstallaties",
    "Vereenvoudigde aanvraagprocedure via MijnISDE"
  ]
};

export default function AutoGeneratedBlogArticle() {
  return (
    <>
      <SEO
        title={`${post.title} | EnerCalculatie`}
        description={post.description}
        canonical={`https://www.enercalculatie.nl/blog/${post.slug}`}
      />
      <BlogPostLayout post={post}>
        <p className="text-slate-700 leading-relaxed mb-4">
          Als installateur in de verduurzamingsbranche is het essentieel om op de hoogte te blijven van de laatste ontwikkelingen in subsidieregelingen. De Investeringssubsidie Duurzame Energie (ISDE) van de RVO ondergaat in 2026 enkele belangrijke wijzigingen die direct impact hebben op uw werkzaamheden en advies aan klanten.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-3">Verhoogde subsidiebedragen voor hybride warmtepompen</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Vanaf 1 januari 2026 worden de subsidiebedragen voor hybride warmtepompen met gemiddeld 15% verhoogd. Dit komt omdat de overheid de transitie van cv-ketels naar duurzamere alternatieven wil versnellen. Voor een gemiddelde hybride warmtepomp kunt u nu rekenen op €1.800 subsidie, tegenover €1.550 in 2025.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-3">Nieuwe isolatie-eisen bij warmtepompinstallaties</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          Een belangrijke wijziging is de verplichting om bij installatie van een warmtepomp (volledig elektrisch of hybride) minimaal twee aanvullende isolatiemaatregelen te treffen. Denk hierbij aan vloerisolatie, spouwmuurisolatie of dakisolatie. Deze maatregelen moeten worden gecertificeerd via een erkende energieadviseur.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-3">Vereenvoudigde aanvraagprocedure</h2>
        <p className="text-slate-700 leading-relaxed mb-4">
          De RVO introduceert in 2026 het nieuwe platform MijnISDE, waar u als installateur namens uw klant de subsidieaanvraag kunt indienen. Het grote voordeel: u kunt direct zien of alle benodigde documenten in orde zijn en ontvangt binnen 2 weken een voorlopige toezegging.
        </p>

        <p className="text-slate-700 leading-relaxed mb-4">
          Tip: Vergeet niet uw klanten te informeren over deze wijzigingen. Een goed geïnformeerde klant begrijpt beter waarom bepaalde investeringen nodig zijn en zal sneller overgaan tot verduurzaming van de woning.
        </p>
      </BlogPostLayout>
    </>
  );
}