import { BlogPostLayout } from './BlogPostLayout';
import { blogPosts } from '../../content/blogPosts';

const post = blogPosts.find((p) => p.slug === 'hybride-warmtepomp-business-case')!;

export function HybrideWarmtepompBusinessCaseArticle() {

  return (
    <BlogPostLayout post={post}>
<p className="text-slate-700 leading-relaxed mb-4">Een hybride warmtepomp is een aantrekkelijk alternatief voor bestaande gasketels. Door de combinatie van een gasketel en een warmtepomp kan de warmtevraag van een woning op een duurzame en kostenefficiënte manier worden gedekt.</p> <h2 className="text-xl md:text-2xl font-bold text-slate-800 mt-8 mb-4">Hoe werkt een hybride warmtepomp?</h2> <p className="text-slate-700 leading-relaxed mb-4">Een hybride warmtepomp werkt door de warmtevraag van een woning te dekken met een combinatie van een gasketel en een warmtepomp. De gasketel zorgt voor de baseload, terwijl de warmtepomp de pieklast dekt. Dit resulteert in een meer efficiente en duurzame warmtevoorziening.</p> <h2 className="text-xl md:text-2xl font-bold text-slate-800 mt-8 mb-4">Wat zijn de voordelen van een hybride warmtepomp?</h2> <p className="text-slate-700 leading-relaxed mb-4">Een hybride warmtepomp biedt verschillende voordelen, waaronder een besparing van meer dan 40% op de energiekosten, een verlaging van de CO2-uitstoot en een hogere efficiëntie dan traditionele gasketels.</p> <h2 className="text-xl md:text-2xl font-bold text-slate-800 mt-8 mb-4">Hoe kan ik de business case voor een hybride warmtepomp onderbouwen?</h2> <p className="text-slate-700 leading-relaxed mb-4">U kunt de business case voor een hybride warmtepomp onderbouwen door de energiekosten te berekenen, de ISDE-subsidie te berekenen en de interviews met tevreden klanten te delen. Meer informatie over de ISDE-subsidie vindt u op <a href="/blog/isde-subsidie-warmtepompen" className="text-brand-primary-text font-semibold hover:underline">ISDE-subsidie voor warmtepompen</a>. Om de energiekosten te berekenen, kunt u ons rekentool voor warmtepompen gebruiken, dat te vinden is op <a href="/rekentool-warmtepomp" className="text-brand-primary-text font-semibold hover:underline">rekentool warmtepomp</a>.</p> <h2 className="text-xl md:text-2xl font-bold text-slate-800 mt-8 mb-4">Hoe EnerCalculatie hiermee omgaat</h2> <p className="text-slate-700 leading-relaxed mb-4">EnerCalculatie biedt een rekentool voor warmtepompen, waarmee u de energiekosten en de ISDE-subsidie kunt berekenen. Ons rekentool is ontwikkeld om u te helpen bij het maken van een business case voor een hybride warmtepomp. Meer informatie over onze diensten vindt u op <a href="/rekentool-warmtepomp" className="text-brand-primary-text font-semibold hover:underline">rekentool warmtepomp</a>.</p>
    </BlogPostLayout>
  );
}
